version: "3"

networks:
  gift.net:
    driver: bridge

services:
  web:
    image: canals/php:latest
    ports:
      - "17000:80"
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache-iutnc.univ-lorraine.fr:3128
    volumes:
      - ./appli/public:/var/www/html
      - ./appli/src:/var/www/src
    networks:
      - gift.net
    working_dir: /var/www/src
    depends_on:
      - database


  database:
    image: mariadb:latest
    ports:
      - "17001:3306"
    networks:
      gift.net:
        aliases:
          - gift.db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}


  dbAdmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "17002:80"
    environment:
      - PMA_HOST=gift.db
    networks:
      - gift.net
    depends_on:
      - database
